<script setup lang="ts">
import { computed } from "vue";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import { resolveIcon, escapeHtml } from "../shared/core";
import { registerSymbol } from "../../src/sprite-registry";

const props = withDefaults(defineProps<{
  name?: IconName;
  icon?: AstroIconImport;
  size?: number | string;
  width?: number | string;
  height?: number | string;
  title?: string;
  desc?: string;
  isInline?: boolean;
}>(), { isInline: false });

const isInline = computed(() => props["isInline"]);

const rendered = computed(() =>
  resolveIcon(
    { name: props.name as string | undefined, icon: props.icon, size: props.size, width: props.width, height: props.height, title: props.title, desc: props.desc },
    "vue"
  )
);

if (!isInline.value) {
  registerSymbol(
    rendered.value.symbolId,
    rendered.value.symbolBody,
    rendered.value.symbolViewBox,
  );
}

const isSSR = typeof document === "undefined";

const spriteHtml = computed(() => {
  const r = rendered.value;
  let html = "";
  if (isSSR) {
    html += `<symbol id="${r.symbolId}" viewBox="${r.symbolViewBox}">${r.symbolBody}</symbol>`;
  }
  if (props.title) html += `<title>${escapeHtml(props.title)}</title>`;
  if (props.desc) html += `<desc>${escapeHtml(props.desc)}</desc>`;
  html += `<use href="#${r.symbolId}" />`;
  return html;
});

function mergeAttrs(
  base: Record<string, unknown>,
  dataAttr: { name: string; value: string } | undefined,
  extra: Record<string, unknown>,
): Record<string, unknown> {
  return {
    ...base,
    ...(dataAttr ? { [dataAttr.name]: dataAttr.value } : {}),
    ...extra,
  };
}
</script>

<template>
  <svg
    v-if="isInline"
    v-bind="mergeAttrs(rendered.attrs, rendered.dataAttr, $attrs)"
    v-html="rendered.inner"
  />
  <svg
    v-else
    v-bind="
      mergeAttrs(
        rendered.attrs,
        rendered.dataAttr,
        $attrs,
      )
    "
    v-html="spriteHtml"
  />
</template>
