<script lang="ts">
  import type { AstroIconImport } from "../../typings/astro-icon-import";
  // @ts-ignore generated by typegen
  import type { Icon as IconName } from "virtual:astro-iconset";
  import { resolveIcon, escapeHtml } from "../shared/core";
  import { registerSymbol } from "../../src/sprite-registry";

  export let name: IconName | undefined = undefined;
  export let icon: AstroIconImport | undefined = undefined;
  export let size: number | string | undefined = undefined;
  export let width: number | string | undefined = undefined;
  export let height: number | string | undefined = undefined;
  export let title: string | undefined = undefined;
  export let desc: string | undefined = undefined;
  export let isInline: boolean | undefined = undefined;

  $: resolved = resolveIcon({ name: name as string | undefined, icon, size, width, height, title, desc }, "svelte");

  $: dataAttrObj = resolved.dataAttr
    ? { [resolved.dataAttr.name]: resolved.dataAttr.value }
    : {};

  $: if (!isInline) {
    registerSymbol(
      resolved.symbolId,
      resolved.symbolBody,
      resolved.symbolViewBox,
    );
  }

  let isSSR = typeof document === "undefined";

  $: spriteHtml =
    (isSSR
      ? `<symbol id="${resolved.symbolId}" viewBox="${resolved.symbolViewBox}">${resolved.symbolBody}</symbol>`
      : "") +
    (title ? `<title>${escapeHtml(title)}</title>` : "") +
    (desc ? `<desc>${escapeHtml(desc)}</desc>` : "") +
    `<use href="#${resolved.symbolId}" />`;
</script>

{#if isInline}
<svg {...resolved.attrs} {...$$restProps} {...dataAttrObj}>
  {@html resolved.inner}
</svg>
{:else}
<svg
  {...resolved.attrs}
  {...$$restProps}
  {...dataAttrObj}
>
  {@html spriteHtml}
</svg>
{/if}
