/** @jsxRuntime automatic */
/** @jsxImportSource solid-js */
import type { JSX, Component } from "solid-js";
import { splitProps } from "solid-js";
import { isServer } from "solid-js/web";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import { resolveIcon, escapeHtml } from "../shared/core";
import { registerSymbol } from "../../src/sprite-registry";

type BaseProps = JSX.SvgSVGAttributes<SVGSVGElement> & {
  size?: number | string;
  title?: string;
  desc?: string;
  isInline?: boolean;
};

type IconProps =
  | (BaseProps & { name: IconName; icon?: never })
  | (BaseProps & { icon: AstroIconImport; name?: never });

const Icon: Component<IconProps> = (rawProps) => {
  const [local, rest] = splitProps(rawProps, [
    "name", "icon", "size", "width", "height", "title", "desc", "isInline",
  ]);

  const { attrs, inner, symbolId, symbolBody, symbolViewBox, dataAttr } = resolveIcon(
    {
      name: local.name as string | undefined,
      icon: local.icon,
      size: local.size,
      width: local.width as number | string | undefined,
      height: local.height as number | string | undefined,
      title: local.title,
      desc: local.desc,
    },
    "solid"
  );

  const dataProps = dataAttr ? { [dataAttr.name]: dataAttr.value } : {};

  if (local.isInline) {
    return <svg {...attrs} {...rest} {...dataProps} innerHTML={inner} />;
  }

  registerSymbol(symbolId, symbolBody, symbolViewBox);

  let innerHtml = "";
  if (isServer) {
    innerHtml += `<symbol id="${symbolId}" viewBox="${symbolViewBox}">${symbolBody}</symbol>`;
  }
  if (local.title) {
    innerHtml += `<title>${escapeHtml(local.title)}</title>`;
  }
  if (local.desc) {
    innerHtml += `<desc>${escapeHtml(local.desc)}</desc>`;
  }
  innerHtml += `<use href="#${symbolId}" />`;

  return (
    <svg
      {...attrs}
      {...rest}
      {...dataProps}
      innerHTML={innerHtml}
    />
  );
};

export default Icon;
