/** @jsxRuntime automatic */
/** @jsxImportSource react */
import type { SVGProps } from "react";
import type { AstroIconImport } from "../../typings/astro-icon-import";
// @ts-ignore generated by typegen
import type { Icon as IconName } from "virtual:astro-iconset";
import { resolveIcon, escapeHtml } from "../shared/core";
import { registerSymbol } from "../../src/sprite-registry";

type BaseProps = Omit<SVGProps<SVGSVGElement>, "name" | "ref"> & {
  size?: number | string;
  title?: string;
  desc?: string;
  isInline?: boolean;
};

type IconProps =
  | (BaseProps & { name: IconName; icon?: never })
  | (BaseProps & { icon: AstroIconImport; name?: never });

export default function Icon(props: IconProps) {
  const { name, icon, size, width, height, title, desc, isInline, ...rest } = props;
  const { attrs, inner, symbolId, symbolBody, symbolViewBox, dataAttr } = resolveIcon(
    { name: name as string | undefined, icon, size, width: width as number | string | undefined, height: height as number | string | undefined, title, desc },
    "react"
  );

  const dataProps = dataAttr ? { [dataAttr.name]: dataAttr.value } : {};

  if (isInline) {
    return (
      <svg
        {...(attrs as SVGProps<SVGSVGElement>)}
        {...rest}
        {...dataProps}
        dangerouslySetInnerHTML={{ __html: inner }}
      />
    );
  }

  registerSymbol(symbolId, symbolBody, symbolViewBox);

  let html = "";
  if (typeof document === "undefined") {
    html += `<symbol id="${symbolId}" viewBox="${symbolViewBox}">${symbolBody}</symbol>`;
  }
  if (title) html += `<title>${escapeHtml(title)}</title>`;
  if (desc) html += `<desc>${escapeHtml(desc)}</desc>`;
  html += `<use href="#${symbolId}" />`;

  return (
    <svg
      {...(attrs as SVGProps<SVGSVGElement>)}
      {...rest}
      {...dataProps}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
